### ISSUE TITLE
github markdown checklist render bug

### ISSUE THREAD

**Issue by ghost** [gonzaloserrano/go-nzalo#2]
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9

**Comment by gonzaloserrano** [comment]
If any GH employee reads this i found the reason: to type `]` you need the alt key, so in case you press the space after using alt too you generate a _weird_ space character which provokes the incorrect rendering.

e.g now this works:
- [ ] 1
- [ ] 2
- [ ] 3
- [ ] 4
- [ ] 5
- [ ] 6
- [ ] 7
- [ ] 8
- [ ] 9
